Fix: attendance form view - remove invisible attributes causing OWL error
The invisible='not check_in_zone_id' attributes were causing
OwlError: field is undefined because OWL couldn't find the field
in the view's model at parse time. Changed to optional='hide' for
all GPS/geo-fence fields.